apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-config.yaml
  - postgres-db.yaml
  - mongodb.yaml
  - redis.yaml
  - product-catalog.yaml
  - product-inventory.yaml
  - order-management.yaml
  - shipping-handling.yaml
  - contact-support.yaml
  - ecommerce-ui.yaml
  - ecommerce-ui-gateway.yaml
