apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
  labels:
    app: product-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-inventory
  template:
    metadata:
      labels:
        app: product-inventory
    spec:
      containers:
        - name: product-inventory
          image: product-inventory
          ports:
            - containerPort: 3002
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: product-inventory-service
spec:
  selector:
    app: product-inventory
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
