apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-handling
  labels:
    app: shipping-handling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-handling
  template:
    metadata:
      labels:
        app: shipping-handling
    spec:
      containers:
        - name: shipping-handling
          image: shipping-handling
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-handling-service
spec:
  selector:
    app: shipping-handling
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
