apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-support
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: contact-support
          image: contact-support:prod-v1.0.0
