apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: order-management
          image: order-management:prod-v1.0.0
