apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: product-inventory
          image: product-inventory:prod-v1.0.0
