global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - 'prometheus_rules.yml'

scrape_configs:
  - job_name: 'product-catalog'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product-catalog:3001']

  - job_name: 'product-inventory'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product-inventory:3002']

  - job_name: 'shipping-handling'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['shipping-handling:8080']

  - job_name: 'contact-support'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['contact-support:8000']

  - job_name: 'order-management'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-management:9090']

  - job_name: 'ecommerce-ui'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ecommerce-ui:4000']

