apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ecommerce-ui
          image: ecommerce-ui:dev
          resources:
            requests:
              cpu: 4m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
