apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecom-dev

resources:
  - ../../base
  - secret.yaml
  # - vpa.yaml

patches:
  - path: config-patch.yaml
  - path: postgres-db.yaml
  - path: mongodb.yaml
  - path: redis.yaml
  - path: product-catalog.yaml
  - path: product-inventory.yaml
  - path: order-management.yaml
  - path: shipping-handling.yaml
  - path: contact-support.yaml
  - path: ecommerce-ui.yaml

images:
  - name: contact-support
    newName: 271643857832.dkr.ecr.ap-south-1.amazonaws.com/contact-support
    newTag: latest
  - name: ecommerce-ui
    newName: 271643857832.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-ui
    newTag: latest
  - name: order-management
    newName: 271643857832.dkr.ecr.ap-south-1.amazonaws.com/order-management
    newTag: latest
  - name: product-catalog
    newName: 271643857832.dkr.ecr.ap-south-1.amazonaws.com/product-catalog-code
    newTag: latest
  - name: product-inventory
    newName: 271643857832.dkr.ecr.ap-south-1.amazonaws.com/product-inventory
    newTag: latest
  - name: shipping-handling
    newName: 271643857832.dkr.ecr.ap-south-1.amazonaws.com/shipping-handling
    newTag: latest
