apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: config-patch.yaml
  - path: postgres-db.yaml
  - path: mongodb.yaml
  - path: redis.yaml
  - path: product-catalog.yaml
  - path: product-inventory.yaml
  - path: order-management.yaml
  - path: shipping-handling.yaml
  - path: contact-support.yaml
  - path: ecommerce-ui.yaml
