apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: order-management
          image: order-management:dev
          resources:
            requests:
              cpu: 4m
              memory: 430Mi
            limits:
              cpu: 200m
              memory: 512Mi
