apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          resources:
            requests:
              cpu: 2m
              memory: 68Mi
            limits:
              cpu: 100m
              memory: 256Mi
