apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: product-catalog
          image: product-catalog:dev
          resources:
            requests:
              cpu: 4m
              memory: 43Mi
            limits:
              cpu: 100m
              memory: 128Mi
