apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecom-secrets
  namespace: ecom-dev
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-kv-backend
    kind: ClusterSecretStore
  target:
    name: ecom-secrets
  data:
    - secretKey: postgres-username
      remoteRef:
        key: "postgres-secret"
        property: "POSTGRES_USER"
    - secretKey: postgres-password
      remoteRef:
        key: "postgres-secret"
        property: "POSTGRES_PASSWORD"