apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-handling
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: shipping-handling
          image: shipping-handling:dev
          resources:
            requests:
              cpu: 1m
              memory: 2Mi
            limits:
              cpu: 50m
              memory: 64Mi
