apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-handling
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: shipping-handling
          image: shipping-handling:dev
