spring.application.name=order-management
server.port=9090
server.address=0.0.0.0
PRODUCT_INVENTORY_API_HOST=http://localhost
PRODUCT_CATALOG_API_HOST=http://localhost
SHIPPING_HANDLING_API_HOST=http://localhost

# Database Configurations
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update